service: puppeteer-scraper

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: ${opt:stage, "dev"}

functions:
  scraper:
    memorySize: 512
    timeout: 900
    image:
      uri: 381491857310.dkr.ecr.us-east-1.amazonaws.com/scraper:latest
      command:
        - dist/index.handler